---
- name: Reset all service accounts
  hosts: SHANEWVM # PowerShell Module is installed here
  gather_facts: false
  vars_files:
    - service_account_vault.yml
  tasks:
    - name: Reset service account credentials
      microsoft.ad.user:
        identity: "CN={{ item.key }},OU=<DISTINGUISHED_NAME>" # DistinguishedName of Account being set in AD - Key is Username in vault file
        password: "{{ item.value }}" # Password for AD Service Account - Value is Password in vault file
        domain_server: "{{ domain_server }}" # DC
      loop: "{{ passwords | dict2items }}" # Transforms the passwords dictionary into a list, so we can loop thru it
...

