---
 
- name: Install web server
  hosts: all
  become: true
  become_user: root
  vars_files: vars/customvars
  tasks:
 
  - name: Install packages
    ansible.builtin.yum:
      state: present
      name: {{ item }}
    loop:
      - {{ webstuff }}
      - {{ sslstuff }}
    failed_when:
        - ansible_facts['distribution'] not in ['CentOS','RedHat']
        - 'Host  does not meet minimal requirements'
 
  - name: Create /tmp/index.html
    ansible.builtin.copy:
      src: /tmp/index.html
      dest: /var/www/html
    register: copy_result
 
  - name: Restart web server service
    ansible.builtin.service:
      name: {{ webstuff }}
      state: restarted
    when: copy_result.failed == false
 
  - name: Open firewall ports
    ansible.builtin.firewalld:
      zone: public
      service: {{ item }}
      permanent: true
      immediate: yes
      state: enabled
    loop:
      - http
      - https
...

