---
- name: Establish repos on remote hosts
  hosts: localhost
  tasks:
    - name: install apache
      dnf:
        name: httpd
        state: latest

    - name: enable apache 
      service:  
        name: httpd
        state: started  
        enabled: true

    - name: open apache in firewall
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      
    - name: Establish BaseOS in /var/www/html so remote hosts can reach repo
      file:
        src: /reposerver/BaseOS
        dest: /var/www/html/BaseOS
        state: link

    - name: Establish AppStream in /var/www/html so remote hosts can reach repo
      file:
        src: /reposerver/AppStream
        dest: /var/www/html/AppStream
        state: link

    - name: Apply context to /reposerver for httpd so it can dish out content
      sefcontext:
        target: '/reposerver(/.*)?'
        setype: httpd_sys_content_t
        state: present
    
    - name: Run a restorecon to lock in the SELinux context settings
      command:  restorecon -Rv /reposerver
