---
- name: Notification for Reboot
  hosts: all
  become_user: root
  become: true
  gather_facts: false
  tasks:
  - name: "Check for reboot required"
    ansible.builtin.command:
      cmd: needs-restarting -r
    register: restart_out
    failed_when: false
    changed_when: false  
  - name: "Generate output"
    debug: 
      msg: "{{ restart_out.stdout }}"
    failed_when: "'Reboot is required' in restart_out.stdout"
...
