---
- name: Setup user accounts and add to groups
  hosts: all
  vars_files:
    users.yml
  tasks:

    - name: Remove groups
      ansible.builtin.group:
        name: "{{ item.grp }}"
        state: absent
      loop: "{{ users }}"

    - name: Remove user
      ansible.builtin.user:
        user: "{{ item.username }}"
        groups: profs
        append: yes
        state: absent
      loop: "{{ users }}"
