---
- name: Setup groups
  hosts: all
  vars_files:
    task7file.yml
  tasks:

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.grp }}"
        state: present
      loop: "{{ users }}"

- name: Setup user accounts and add to groups node1
  hosts: VM1.SHANESHOMELAB.COM 
  gather_facts: false
  vars_files:
    task7file.yml
  tasks:

    - name: Create users
      ansible.builtin.user:
        user: "{{ item.username }}"
        groups: "{{ item.grp }}"
        append: yes
      loop: "{{ users }}"
      when: "{{ item.grp  == 'profs'}}"

- name: Setup user accounts and add to groups node2
  hosts: VM2.SHANESHOMELAB.COM
  gather_facts: false
  vars_files:
    task7file.yml
  tasks:

    - name: Create users
      ansible.builtin.user:
        user: "{{ item.username }}"
        groups: "{{ item.grp }}"
        append: yes
      loop: "{{ users }}"
      when: "{{ item.grp  == 'students'}}"
 
- name: Set passwords on user accounts node1
  hosts: VM1.SHANESHOMELAB.COM
  gather_facts: false
  ignore_errors: true
  vars_files:
    task7file.yml
  tasks:

    - name: Set pasword on users node1
      ansible.builtin.shell: echo {{ item.pwd }} | passwd {{ item.username }} --stdin
      loop: "{{ users }}"

- name: Set passwords on user accounts node2
  hosts: VM2.SHANESHOMELAB.COM
  gather_facts: false
  ignore_errors: true
  vars_files:
    task7file.yml
  tasks:

    - name: Set pasword on users node2
      ansible.builtin.shell: echo {{ item.pwd }} | passwd {{ item.username }} --stdin
      loop: "{{ users }}"
