---
- name: Update report on remote hosts
  hosts: all
  become: true
  become_user: root
  tasks:

    - name: Copy report to remote hosts
      ansible.builtin.copy:
        src: ./report.txt
        dest: "/tmp/{{ ansible_hostname | upper }}-report.txt"

    - name: Update hostname
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname | upper }}-report.txt"
        regexp: '^HOSTNAME='
        line: "HOSTNAME={{ ansible_hostname }}"

    - name: Update memory
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname | upper }}-report.txt"
        regexp: '^MEMORY='
        line: "MEMORY={{ ansible_memory_mb.real.total }}"
    - name: Update disk size
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname | upper }}-report.txt"
        regexp: '^PRIMARY_DISK_SIZE='
        line: "PRIMARY_DISK_SIZE={{ ansible_devices.sda.size }}"

    - name: Update disk = present
      stat:
        path: /dev/sdb
      register: sdb_exists
    - name: Update file with content
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname | upper }}-report.txt"
        regexp: '^SECOND_DISK='
        line: "SECOND_DISK=PRESENT"
      when: sdb_exists.stat.exists

    - name: Update disk = absent
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname | upper }}-report.txt"
        regexp: '^SECOND_DISK='
        line: "SECOND_DISK=ABSENT"
      when: not sdb_exists.stat.exists
